<?php

$labels = array();
$labels['keyboard_shortcuts'] = 'Бързи клавиши';
$labels['show'] = ' ';
$labels['help'] = 'Помощ';
$labels['selectallvisiblemessages'] = 'Избери всички видими съобщения';
$labels['markallvisiblemessagesasread'] = 'Маркирай всички видими съобщения като прочетени';
$labels['markselected'] = 'Маркирай всички избрани съобщения като прочетени/непрочетени';
$labels['title'] = 'Бързи клавиши';

?>
